workflows:
  flutter_workflow:
    name: StatSense_WF
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
        - app_store_credentials
      vars:
        GOOGLE_PLAY_TRACK: "beta"
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: "*"
          include: true
    scripts:
      - name: Get Flutter Packages
        script: flutter packages pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - techdevmd@gmail.com
