workflows:
  my_flutter_workflow:
    name: StatSense_WF
    environment:
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      script:
        - name: before_build
          script: flutter pub get
        - name: build
          script: flutter build ios --release --no-codesign
        - name: after_build
          script: echo "Build finished successfully!"
    artifacts:
      - build/ios/Runner.ipa
