name: nhl
description: "An app to help boost your NHL Fantasy league streamer targets"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  intl: ^0.17.0
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.9
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic.png"
  adaptive_icon_background: "#2d2d2d"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: Lato-Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Lato-Bold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: Lato-Light
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
    - family: Lato-Thin
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf

  assets:
    - assets/images/team_logos/
    - assets/images/splash.png
  uses-material-design: true
