name: nhl
description: "An app to help boost your NHL Fantasy league streamer targets"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  intl: ^0.17.0
  path_provider: ^2.1.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/ic_launcher.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
  image_path_android: "assets/images/ic_launcher.png"
  image_path_ios: "assets/images/ic_launcher.png"
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Rowdies-Bold
      fonts:
        - asset: assets/fonts/Rowdies-Bold.ttf
    - family: Rowdies-Regular
      fonts:
      - asset: assets/fonts/Rowdies-Regular.ttf
    - family: Rowdies-Light
      fonts:
        - asset: assets/fonts/Rowdies-Light.ttf
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Inter-Regular
      fonts:
      - asset:
          assets/fonts/Inter-Bold.ttf

  assets:
    - assets/images/backdrop.gif
    - android/app/src/main/res/appicon.png
    - assets/images/team_logos/
  uses-material-design: true
